### ISSUE TITLE
Clean up state types

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#175] opened 2016-05-25 16:30 UTC
State types are not working well for martyrs. Need to clean up--perhaps type="saint"?

Current state type values on persons are:
office
confession
saint
martyr
vocation
occupation

Element contents for type="saint" currently includes
St.
the martyr
(Martyrius)

state role values on persons are currently:
monk
bishop
metropolitan
patriarch
catholicos
abbot
saint
maphrian
priest
historian

**Comment by nathangibson** [comment] 2016-07-19 16:00
@dlschwartz @davidamichelson @jsaintlauren (cc: @wsalesky, @tacarlson )
Re. state elements for persons: I am trying to figure out how to process "martyr", "monk", "slave", etc. for the new saint records I will be creating from the spreadsheet J-N is working on. This relates to the broader question of the state element and its attributes. No. 1 below is the most urgent question of the 3 to resolve.

1. Currently we are designating martyrs like so: 
```
<state type="martyr" source="#bib8-7"><p>Martyr</p></state>
```
As we discussed before, perhaps we should change the `@type` to `"saint"`. In addition, I would recommend standardizing the `<p>Martyr</p>` as `<label>martyr</label>` instead. This would bring our usage in line with the way we have done confessions, and would be more friendly to a controlled vocabulary. See examples at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-state.html. **Are there any objections to my doing this?** If we did so, we'd also need Winona to tweak the XSLT. 

2. I would recommend we keep the other state types, except possibly `"vocation"`. Does anyone remember what we wanted to use that for? Was it for "monk"? 

3. I recommend we switch from using `@role` on state to putting these values inside a `<label>` inside state. Again, this would bring our usage into line with "confession". Also, `@role` seems intended specifically to be used to provide further information about names (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.naming.html#tei_att.role). We can add a `<desc>` inside state when we want to provide more information. So the following (from http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/26/tei)
```
<state type="office" role="metropolitan">
     <desc xml:lang="en">metropolitan bishop of <placeName ref="http://syriaca.org/place/78">Edessa</placeName></desc>
</state>
```
would become
``
<state type="office">
     <label>metropolitan</label>
     <desc xml:lang="en">metropolitan bishop of <placeName ref="http://syriaca.org/place/78">Edessa</placeName></desc>
</state>
```
Thoughts?

**Comment by nathangibson** [comment] 2016-07-19 16:07
Oops, that didn't come through right. Editing ...

**Comment by nathangibson** [comment] 2016-07-19 19:33
In our discussion tonight we noticed that in addition to the human-readable label the Gazetteer uses `@ref` to point to the controlled vocab. We're wondering whether the ref would itself be enough for  states in person records (pulling the human-readable label from the controlled vocab), or whether the human-readable label should also be included in every record. If the latter, perhaps we would want a maintenance script to periodically update the human-readable label to keep it in sync with the controlled vocab. To discuss on Thursday.

**Comment by nathangibson** [comment] 2016-07-20 13:21
Note to self: Adjust persons spreadsheet2tei XSLT and template according to the decision we make here. Also make sure that persons from https://docs.google.com/spreadsheets/d/1ruAawFWhOcTeGBzjgMLv_akzGRj3-DjxljJ6eFy6qOE/edit#gid=0 (persons 3002-3017) are in compatible format.

**Comment by nathangibson** [comment] 2016-08-02 19:19
Use `@ref` to link to controlled vocab, and `<label>` is optional just for human readability. Keep type for now since it's useful as a label. 

Also add state type="author"

Notes from Dan: 
Identify the work someone did using state (occupation, office, vocation):
<state type=“office”> for state roles: emperor, governor, town councilor, etc. 
<state type=“vocation”> for religious roles: bishop, deacon, monk, virgin of the church, etc.
<state type=“occupation”> for anything else: soldier, tradesman, merchant, farmer, baker, etc.
Identify other states as well
<state type=“citizenship”> for references to a person’s citizenship in an empire, city, etc.
<state type=“socialRank”> for references to rank, noble birth, common birth, slavery, etc.
<state type=”martyr”>
<state type=”confessor”>
Identify physical characteristics
<trait type=“physical”> for hair color, eye color, stature, etc

Once we have the controlled vocab, show it to Dan so he can add to it as needed for SPEAR.

**Comment by wlpotter** [comment] 2023-05-26 19:15
Closing as a duplicate of #905. I will reference this discussion there.

**Closed by wlpotter** 2023-05-26 19:15 UTC
