### ISSUE TITLE
Update citations for GEDSH in all records and point to URIS for GEDSH (perhaps in the bibl record not in the place/person record)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#743] opened 2018-11-27 17:38 UTC
point to the URIs from the new eGEDSH

**Comment by wlpotter** [comment] 2020-05-20 21:25
@davidamichelson I'm not sure exactly what change we want here.

I have the script that connects Syriaca URIs and e-GEDSH entry URIs. I've only run it on person records, but I can run it on places as well. We can then include the e-GEDSH URI in the `tei:idno` list.

If I understand this issue right, though, we would want to change the current bibls for the record's GEDSH entry:

```
<bibl xml:id="bib78-1">
                        <author>A. Harrak</author>
                        <title level="a" xml:lang="en">183. Edessa</title>
                        <title level="m" xml:lang="en">The Gorgias Encyclopedic Dictionary of the Syriac Heritage</title>
                        <ptr target="http://syriaca.org/bibl/1"/>
                        <citedRange unit="pp">138-139</citedRange>
                    </bibl>
```
To point at instead the e-GEDSH version? So the new bibl would be:

```
<bibl xml:id="bib78-1">
                        <author>A. Harrak</author>
                        <title level="a" xml:lang="en">183. Edessa</title>
                        <title level="m" xml:lang="en">The Gorgias Encyclopedic Dictionary of the Syriac Heritage</title>
                        <ptr target="http://syriaca.org/bibl/1"/>
                        <citedRange unit="entry">https://gedsh.bethmardutho.org/Edessa</citedRange>
                    </bibl>
```

Or will the e-GEDSH citation be a new bibl?

**Comment by wlpotter** [comment] 2020-05-20 21:27
Note that since we do not have bibl records for individual entries in GEDSH, we will need to use some form of tei:citedRange to point at the entry.

Alternatively we could replace the `tei:pter/@target` attribute value, currently pointing at the Syriaca Bibl record for GEDSH, with the entry URI

**Comment by davidamichelson** [comment] 2020-05-26 17:32
Need to work out next steps

**Comment by davidamichelson** [comment] 2020-06-15 17:29
- [ ] @wlpotter Please check if we have bibl URIS for all articles

- [ ] @wlpotter Please update all bibl records for GEDSH articles to include the URI to egedsh as their URL

- [ ] @wlpotter Please find all Place/Person/Work records that cite individual GEDSH articles and point them to the article level Syriaca bibl URIs instead.

**Comment by davidamichelson** [comment] 2020-06-15 17:42
Currently, place/388 has this bibl:

```
<bibl xml:id="bib388-1">
<author>G. A. Kiraz </author>
<title level="a" xml:lang="en">354. Mark, Monastery of St.</title>
<title level="m" xml:lang="en">
The Gorgias Encyclopedic Dictionary of the Syriac Heritage
</title>
<ptr target="http://syriaca.org/bibl/1"/>
<citedRange unit="pp">269-270</citedRange>
</bibl>
```

and we have a record for bibl/363 which is the GEDSH article.

Please make the following updates.

In bibl/363 Currently:
```
<biblStruct>
<analytic>
<author>
<forename>G. A.</forename>
<surname>Kiraz </surname>
</author>
<title level="a" xml:lang="en">Mark, Monastery of St</title>
</analytic>
<monogr>
```
Change to:
```
<biblStruct>
<analytic>
<author>
<forename>G. A.</forename>
<surname>Kiraz </surname>
</author>
<title level="a" xml:lang="en">Mark, Monastery of St</title>
<ref target="https://gedsh.bethmardutho.org/Mark-Monastery-of-St"/>
</analytic>
<monogr>
```

Next in place/338

find /TEI/text/body/listPlace/place/bibl/title/@level="a" and textnode "354. Mark, Monastery of St."
```
<bibl xml:id="bib388-1">
                        <author>G. A. Kiraz </author>
                        <title level="a" xml:lang="en">354. Mark, Monastery of St.</title>
                        <title level="m" xml:lang="en">The Gorgias Encyclopedic Dictionary of the Syriac Heritage</title>
                        <ptr target="http://syriaca.org/bibl/1"/>
                        <citedRange unit="p">269-270</citedRange>
                    </bibl>
```

Change ` <ptr target="http://syriaca.org/bibl/1"/>`
to ` <ptr target="http://syriaca.org/bibl/363"/>'

**Comment by wlpotter** [comment] 2020-06-15 20:37
A few updates:

- All articles have an associated bibl URI. However, not all of these URIs have a record created. This will enable us to change the `ptr/@target` value in the bibl elements of each Syriaca entity record. (item 3 in the [above comment](https://github.com/srophe/srophe-app-data/issues/743#issuecomment-644268203)).
- I can use a script to find which articles still need records to be created. I can then also, most likely, batch generate bibl records for these articles since most of the data is static (e.g., monograph level info, most of the teiHeader, etc.)
- I can also, of course, use a script to add the GEDSH URI to the bibl records which already exist.

**Comment by wlpotter** [comment] 2020-06-15 20:51
Okay, so having done a bit more digging I think the issue is not a question of if all of the GEDSH article bibl record have been created but rather if all the records are present on the production server.

For example, http://syriaca.org/bibl/192 is not on the production server, but there is a record for it: https://github.com/srophe/srophe-app-data/blob/master/data/bibl/tei/192.xml

I can update the XML data so that the bibl module includes the e-GEDSH URI (and the article number if we would like); I will also update the pointers in all records so that the footnotes point to the correct record.

Do we need to make an app issue for the missing records on production? Or is this part of the upgrade that should be resolved soon?

**Comment by wlpotter** [comment] 2020-06-15 21:47
I have reverted the above two commits as I made a mistake in the script that matched the URIs. Fixing this now and will run the script again.

**Comment by wlpotter** [comment] 2020-06-15 21:55
Note: this does not seem to apply to works. There are no work records with a bibl whose ptr is "http://syriaca.org/bibl/1" which also has an a-level title. 

The `tei:bibl/ptr/@target` attributes have been updated.

**Comment by wlpotter** [comment] 2020-06-15 22:00
@davidamichelson what remains is to add the GEDSH URI to the bibl records. Before I do that, can we discuss whether or not we need/want to add the GEDSH article number as well (e.g. 183 for [Edessa](https://gedsh.bethmardutho.org/Edessa))?

This could potentially go in `/TEI/text/body/biblStruct/monogr/biblScope[@type="entry"]`

**Comment by wlpotter** [comment] 2020-06-16 18:50
This has been fixed in all data.

**Closed by wlpotter** 2020-06-16 18:50 UTC
Labels: 2019-May-Batch-Changes, enhancement
