### ISSUE TITLE
Change relationship refs to include full URIs

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#21] opened 2016-02-26 17:48 UTC
From: 
`<relation name="share-a-name" mutual="#place-10  http://syriaca.org/place/995"/>`

to:
`<relation name="share-a-name" mutual="http://syriaca.org/place/10  http://syriaca.org/place/995"/>`

**Comment by wlpotter** [comment] 2023-05-26 19:25
Duplicate of #809

**Closed by wlpotter** 2023-05-26 19:25 UTC
Labels: enhancement
